split:
  test_size: 0.2
  random_state: 42

preprocessing:
  numeric: standard_scaler
  categorical: one_hot

models:
  random_forest:
    n_estimators: [50, 100, 200]
    max_depth: [5, 10, 20]
  gradient_boosting:
    n_estimators: [50, 100, 200]
    max_depth: [3, 5, 7]
    learning_rate: [0.01, 0.1, 0.2]
  linear_regression:
    fit_intercept: [true, false]


